CREATE OR ALTER view [dbo].[v_u_od_a] (
	whse_code, od_rid, odh_rid, ob_lno, ob_oid, ob_type, batch_oid, batch_type,batch_lno, ob_lno_stt, sku, pkg, lot, uc1, uc2, uc3, org_qty, ord_qty, plan_qty, bal_plan_qty,  bal_cmp_qty, sched_qty, ship_qty, cmp_qty, ord_uom, cust_oid, cust_lno, cust_part,  sell_uom, sell_mult, unit_price, hold, fill_short, tag, cont, mod_resource, mod_user, mod_counter, create_stamp, mod_stamp, force_rpln, host_backordered, reqst_recpt_date, open_ord_qty, ship_to_date_qty, host_order_lno, is_picked_short, kit_line_type,  kit_order_group, kit_comp_mult, kit_end_item_ob_lno, gtin, custom_char_1,  custom_char_2, custom_char_3, custom_char_4, custom_char_5, custom_char_6,  custom_char_7, custom_char_8, custom_char_9, custom_char_10, custom_numeric_1,  custom_numeric_2, custom_numeric_3, custom_numeric_4, custom_numeric_5,  custom_numeric_6, custom_numeric_7, custom_numeric_8, custom_numeric_9,  custom_numeric_10, return_source, backorder_line_action, sms_supply_order_id, buyer_style_num, color_desc, size_desc, trading_partner_item_desc, original_pkg, original_uc1, original_uc2, original_uc3, external_reference, label_char_1, label_char_2, label_char_3, label_char_4, label_char_5, label_char_6, label_char_7, label_char_8, label_char_9, label_char_10, line_item_desc
)  AS 
SELECT whse_code, od_rid, 0 odh_rid, ob_lno, ob_oid, ob_type, batch_oid,  batch_type, batch_lno, ob_lno_stt, sku, pkg, lot, uc1, uc2, uc3, org_qty,  ord_qty, plan_qty, bal_plan_qty, bal_cmp_qty, sched_qty, ship_qty, cmp_qty, ord_uom,  cust_oid, cust_lno, cust_part, sell_uom, sell_mult, unit_price, hold, fill_short,  tag, cont, mod_resource, mod_user, mod_counter, create_stamp, mod_stamp, force_rpln,  host_backordered, reqst_recpt_date, open_ord_qty, ship_to_date_qty, host_order_lno,  is_picked_short, kit_line_type, kit_order_group, kit_comp_mult, kit_end_item_ob_lno,  gtin, custom_char_1, custom_char_2, custom_char_3, custom_char_4, custom_char_5,  custom_char_6, custom_char_7, custom_char_8, custom_char_9, custom_char_10,  custom_numeric_1, custom_numeric_2, custom_numeric_3, custom_numeric_4,  custom_numeric_5, custom_numeric_6, custom_numeric_7, custom_numeric_8,  custom_numeric_9, custom_numeric_10, return_source, backorder_line_action, sms_supply_order_id, buyer_style_num, color_desc, size_desc, trading_partner_item_desc, original_pkg, original_uc1, original_uc2, original_uc3, external_reference, label_char_1, label_char_2, label_char_3, label_char_4, label_char_5, label_char_6, label_char_7, label_char_8, label_char_9, label_char_10, line_item_desc   
FROM od_f 
UNION ALL 
SELECT whse_code, od_rid, odh_rid, ob_lno, ob_oid, ob_type, batch_oid, batch_type,  batch_lno, ob_lno_stt, sku, pkg, lot, uc1, uc2, uc3, org_qty, ord_qty, plan_qty,  bal_plan_qty, bal_cmp_qty, sched_qty, ship_qty, cmp_qty, ord_uom, cust_oid, cust_lno, cust_part, sell_uom, sell_mult, unit_price, hold, fill_short, tag, cont,  mod_resource, mod_user, mod_counter, create_stamp, mod_stamp, force_rpln,  host_backordered, reqst_recpt_date, open_ord_qty, ship_to_date_qty, host_order_lno,  is_picked_short, kit_line_type, kit_order_group, kit_comp_mult, kit_end_item_ob_lno,  gtin, custom_char_1, custom_char_2, custom_char_3, custom_char_4, custom_char_5,  custom_char_6, custom_char_7, custom_char_8, custom_char_9, custom_char_10,  custom_numeric_1, custom_numeric_2, custom_numeric_3, custom_numeric_4,  custom_numeric_5, custom_numeric_6, custom_numeric_7, custom_numeric_8,  custom_numeric_9, custom_numeric_10, return_source, backorder_line_action, sms_supply_order_id, buyer_style_num, color_desc, size_desc, trading_partner_item_desc, original_pkg, original_uc1, original_uc2, original_uc3, external_reference, label_char_1, label_char_2, label_char_3, label_char_4, label_char_5, label_char_6, label_char_7, label_char_8, label_char_9, label_char_10, line_item_desc 
FROM od_h
UNION ALL 
SELECT whse_code, od_rid, odh_rid, ob_lno, ob_oid, ob_type, batch_oid, batch_type,  batch_lno, ob_lno_stt, sku, pkg, lot, uc1, uc2, uc3, org_qty, ord_qty, plan_qty,  bal_plan_qty, bal_cmp_qty, sched_qty, ship_qty, cmp_qty, ord_uom, cust_oid, cust_lno, cust_part, sell_uom, sell_mult, unit_price, hold, fill_short, tag, cont,  mod_resource, mod_user, mod_counter, create_stamp, mod_stamp, force_rpln,  host_backordered, reqst_recpt_date, open_ord_qty, ship_to_date_qty, host_order_lno,  is_picked_short, kit_line_type, kit_order_group, kit_comp_mult, kit_end_item_ob_lno,  gtin, custom_char_1, custom_char_2, custom_char_3, custom_char_4, custom_char_5,  custom_char_6, custom_char_7, custom_char_8, custom_char_9, custom_char_10,  custom_numeric_1, custom_numeric_2, custom_numeric_3, custom_numeric_4,  custom_numeric_5, custom_numeric_6, custom_numeric_7, custom_numeric_8,  custom_numeric_9, custom_numeric_10, return_source, backorder_line_action, sms_supply_order_id, buyer_style_num, color_desc, size_desc, trading_partner_item_desc, original_pkg, original_uc1, original_uc2, original_uc3, external_reference, label_char_1, label_char_2, label_char_3, label_char_4, label_char_5, label_char_6, label_char_7, label_char_8, label_char_9, label_char_10, line_item_desc 
FROM od_a
GO
