UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCCR EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCCR KA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCCR KE' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCCR MT' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCCR VN' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Bandstra' WHERE carrier_service = 'BCNO EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Bandstra' WHERE carrier_service = 'BCNO HY' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'BCNO PG' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Zion Freight' WHERE carrier_service = 'BCSO EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'BURN NW' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Comm Log' WHERE carrier_service = 'FRVY EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Fairon' WHERE carrier_service = 'GBSH BI' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('City Transfer' WHERE carrier_service = 'GBSH SC' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('GLSC US' WHERE carrier_service = 'GLSC US' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD LA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD NS' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD RI' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD SO' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'GVRD SU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'KAML VA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pick Up-1' WHERE carrier_service = 'LDBI NT' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Manitoulin' WHERE carrier_service = 'NOWE AT' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Bandstra' WHERE carrier_service = 'NOWE BC' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'NOWE CO' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('OOP' WHERE carrier_service = 'OUTO PR' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('RTS' WHERE carrier_service = 'SUPP RT' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'VANC DT' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'VANC EA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VANC KA' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('LDB Trk' WHERE carrier_service = 'VANC WE' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Liquid Assets' WHERE carrier_service = 'VLPU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS CR' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS MD' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS NO' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS PQ' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS TU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'VNIS UP' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Spirit Lifters' WHERE carrier_service = 'VSPU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('UNBTL' WHERE carrier_service = 'VUPU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pick Up-5' WHERE carrier_service = 'VWAV PU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pick Up-4' WHERE carrier_service = 'VWCO PU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pick Up' WHERE carrier_service = 'VWCS PU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pick Up-3' WHERE carrier_service = 'VWOT PU' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'WHIS GB' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Squamish Freight' WHERE carrier_service = 'WHIS L1' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Van Kam' WHERE carrier_service = 'WHIS L2' AND carrier_code <> '';
UPDATE lc_f SET carrier_code = UPPER('Pemberton Freight' WHERE carrier_service = 'WHIS L3' AND carrier_code <> '';


