UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCCR EA';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCCR KA';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCCR KE';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCCR MT';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCCR VN';
UPDATE ca_f SET carrier_code = UPPER('Bandstra') WHERE carrier_service ='BCNO EA';
UPDATE ca_f SET carrier_code = UPPER('Bandstra') WHERE carrier_service ='BCNO HY';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='BCNO PG';
UPDATE ca_f SET carrier_code = UPPER('Zion Freight') WHERE carrier_service ='BCSO EA';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='BURN NW';
UPDATE ca_f SET carrier_code = UPPER('Comm Log') WHERE carrier_service ='FRVY EA';
UPDATE ca_f SET carrier_code = UPPER('Fairon') WHERE carrier_service ='GBSH BI';
UPDATE ca_f SET carrier_code = UPPER('City Transfer') WHERE carrier_service ='GBSH SC';
UPDATE ca_f SET carrier_code = UPPER('GLSC US') WHERE carrier_service ='GLSC US';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD EA';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD LA';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD NS';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD RI';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD SO';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='GVRD SU';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='KAML VA';
UPDATE ca_f SET carrier_code = UPPER('Pick Up-1') WHERE carrier_service ='LDBI NT';
UPDATE ca_f SET carrier_code = UPPER('Manitoulin') WHERE carrier_service ='NOWE AT';
UPDATE ca_f SET carrier_code = UPPER('Bandstra') WHERE carrier_service ='NOWE BC';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='NOWE CO';
UPDATE ca_f SET carrier_code = UPPER('OOP') WHERE carrier_service ='OUTO PR';
UPDATE ca_f SET carrier_code = UPPER('RTS') WHERE carrier_service ='SUPP RT';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='VANC DT';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='VANC EA';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VANC KA';
UPDATE ca_f SET carrier_code = UPPER('LDB Trk') WHERE carrier_service ='VANC WE';
UPDATE ca_f SET carrier_code = UPPER('Liquid Assets') WHERE carrier_service ='VLPU';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS CR';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS MD';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS NO';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS PQ';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS TU';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='VNIS UP';
UPDATE ca_f SET carrier_code = UPPER('Spirit Lifters') WHERE carrier_service ='VSPU';
UPDATE ca_f SET carrier_code = UPPER('UNBTL') WHERE carrier_service ='VUPU';
UPDATE ca_f SET carrier_code = UPPER('Pick Up-5') WHERE carrier_service ='VWAV PU';
UPDATE ca_f SET carrier_code = UPPER('Pick Up-4') WHERE carrier_service ='VWCO PU';
UPDATE ca_f SET carrier_code = UPPER('Pick Up') WHERE carrier_service ='VWCS PU';
UPDATE ca_f SET carrier_code = UPPER('Pick Up-3') WHERE carrier_service ='VWOT PU';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='WHIS GB';
UPDATE ca_f SET carrier_code = UPPER('Squamish Freight') WHERE carrier_service ='WHIS L1';
UPDATE ca_f SET carrier_code = UPPER('Van Kam') WHERE carrier_service ='WHIS L2';
UPDATE ca_f SET carrier_code = UPPER('Pemberton Freight') WHERE carrier_service ='WHIS L3';


