:r 01_ddl_view_bol_cont_ldb.sql
:r 02_ddl_view_bol_po_ldb.sql
:r 05_ddl_func_mpack_item_desc_ldb.sql
:r 06_ddl_func_mpack_loc_list_ldb.sql
:r 07_ddl_view_cpack_order_line_ldb.sql
:r 09_ddl_view_mpack_ldb.sql
:r 10_ddl_view_v_u_cm_f_ldb.sql
:r 11_ddl_view_ob_ord_summ_ldb.sql
:r 12_ddl_view_v_ob_ord_stt_summ_ldb.sql
:r 13_ddl_view_v_ob_stager_view_ldb.sql
:r 14_ddl_view_v_u_shipunit_f_ldb.sql
:r 99_delete_script.sql
